version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  blood-donation:
    external:
      name: blood-donation

services:

  explorerdb.blofab.example.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.blofab.example.com
    hostname: explorerdb.blofab.example.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blood-donation

  explorer.blofab.example.com:
    image: hyperledger/explorer:latest
    container_name: explorer.blofab.example.com
    hostname: explorer.blofab.example.com
    environment:
      - DATABASE_HOST=explorerdb.blofab.example.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../network/organizations:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.blofab.example.com:
        condition: service_healthy
    networks:
      - blood-donation