version: '2'

networks: 
  blood-donation:
      external: 
        name: blood-donation

services: 
  
  chaincode-blofab.example.com:
    hostname: chaincode.blofab.example.com
    image: hyperledger/fabric-chaincode:$IMAGE_TAG
    env_file:
      - chaincode.env
    environment:
      - CHAINCODE_CCID=blofab_1:6bd1902d464cb5939cb85e01398fa4f0af2fee24173d466784ee10236be083e2
      - CHAINCODE_ADDRESS=0.0.0.0:7052
    ports: 
      - '7052:7052'
    volumes:
      - ../network/organizations/peerOrganizations/blofab.example.com/chaincode/chaincode.blofab.example.com/tls/:/tls
    container_name: chaincode-blofab.example.com
    networks: 
      - blood-donation
