version: '2'

networks: 
  blood-donation:
      external: 
        name: blood-donation

services: 
  
  ca_blofab:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.blofab.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports: 
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b blofab:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/blofab:/etc/hyperledger/fabric-ca-server
    container_name: ca_blofab
    networks: 
      - blood-donation

